use_frameworks!

target 'GrammarKit_Example' do

    platform :ios, '10.0'
    
    pod 'GrammarKit', :path => '../../../'

    target 'GrammarKit_Tests' do
        inherit! :search_paths
        
    end

end
